AWSTemplateFormatVersion: "2010-09-09"
Description: "Cloud Data Processing Pipeline"
Transform: AWS::Serverless-2016-10-31
Parameters:
  DataIngestTopic:
    Type: String
    MinLength: 1
    Default: "elgo/v1/kitchenappliance1/#" #
    Description: "MQTT Topic Name"

Resources:
  ########################################################################
  # S3
  ########################################################################
  # S3 Buckets
  # Bucket for input data
  IngestDataBucket:
    # DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !Ref LogsBucket
        LogFilePrefix: iot-data-ingest/
      LifecycleConfiguration:
        Rules:
          - Id: ExpirationRule
            Status: Enabled
            ExpirationInDays: "7"

  # Buckets for processed data
  ProcessedDataBucket:
    # DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    DependsOn:
      - S3NotificationLambdaFunction
      - LogsBucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !Ref LogsBucket
        LogFilePrefix: processed-data/
      LifecycleConfiguration:
        Rules:
          - Id: ExpirationRule
            Status: Enabled
            ExpirationInDays: 7
      # NotificationConfiguration: #Update stack with NotificationConfiguration
      #   LambdaConfigurations:
      #     - Event: s3:ObjectCreated:Put
      #       Function: !GetAtt S3NotificationLambdaFunction.Arn
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: prefix
      #               Value: processed-data/
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "This is the logs bucket"
  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: LogsBucket
    Properties:
      Bucket: !Ref LogsBucket
      PolicyDocument:
        Statement:
          - Sid: AllowLogDeliveryFromIngestAndProcessedBuckets
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:PutObject"
            Resource:
              - !Sub "${LogsBucket.Arn}/iot-data-ingest/*"
              - !Sub "${LogsBucket.Arn}/processed-data/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"
  ########################################################################
  # IoT Pipeline
  ########################################################################

  # IoT
  # [To change] Send to Kineis Firehose and to Kinesis Data Stream
  IoTTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Description: "Send IoT Device data in raw format to Kinesis Analytics"
        AwsIotSqlVersion: "2016-03-23"
        RuleDisabled: "false"
        Sql: !Sub 'SELECT *
          FROM "${DataIngestTopic}"'
        Actions:
          - Firehose:
              DeliveryStreamName: !Ref IngestDataDeliveryStream
              RoleArn: !Sub "${IoTTopicRuleRole.Arn}"
              Separator: "\n"
          - Kinesis:
              StreamName: !Ref RawDataIngestStream
              RoleArn: !GetAtt IoTTopicRuleRole.Arn

  # Ingest Data Delivery Stream
  IngestDataDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      S3DestinationConfiguration:
        BucketARN: !GetAtt IngestDataBucket.Arn
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 100
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref IoTDataProcessingLogGroup
          LogStreamName: "IngestDataS3Delivery"
        CompressionFormat: "UNCOMPRESSED"
        EncryptionConfiguration:
          NoEncryptionConfig: "NoEncryption"
        Prefix: "raw-data/"
        RoleARN: !GetAtt IngestDataDeliveryStreamRole.Arn

  # Ingest Data Delivery Stream for Kinesis
  RawDataIngestStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1 # Specify the appropriate number of shards for your use case

  AnomalyDetectionApplication:
    Type: AWS::KinesisAnalytics::Application
    Properties:
      ApplicationCode: |
        CREATE OR REPLACE STREAM "POWER_ANOMALY_STREAM" (
          "deviceLabel" VARCHAR(512),
          "devicePower" DOUBLE,
          "recordedTimestamp" TIMESTAMP,
          "rcfAnomalyScore" DOUBLE
        );
        CREATE OR REPLACE PUMP "POWER_ANOMALY_PUMP" AS
        INSERT INTO "POWER_ANOMALY_STREAM"
        SELECT STREAM
          "deviceLabel",
          "devicePower",
          "recordedTimestamp",
          ANOMALY_SCORE as rcfAnomalyScore
        FROM TABLE(
          RANDOM_CUT_FOREST(
            CURSOR(SELECT STREAM "deviceLabel", "devicePower", "recordedTimestamp" FROM "SOURCE_SQL_STREAM"),
            100, 256, 100000, 5)
        );
      Inputs:
        - NamePrefix: "SOURCE_SQL_STREAM"
          InputSchema:
            RecordColumns:
              - Name: "devicePower"
                SqlType: "DOUBLE"
                Mapping: "$.devicePower"
              - Name: "recordedTimestamp"
                SqlType: "TIMESTAMP"
                Mapping: "$.recordedTimestamp"
              - Name: "deviceLabel"
                SqlType: "VARCHAR(512)"
                Mapping: "$.deviceLabel"
            RecordFormat:
              RecordFormatType: "JSON"
              MappingParameters:
                JSONMappingParameters:
                  RecordRowPath: "$"
          KinesisStreamsInput:
            ResourceARN: !GetAtt RawDataIngestStream.Arn
            RoleARN: !GetAtt KinesisAnalyticsRole.Arn

  AnomalyDetectionApplicationOutput:
    Type: AWS::KinesisAnalytics::ApplicationOutput
    Properties:
      ApplicationName: !Ref AnomalyDetectionApplication
      Output:
        DestinationSchema:
          RecordFormatType: "CSV"
        KinesisFirehoseOutput:
          ResourceARN: !GetAtt processedDataDeliveryStream.Arn
          RoleARN: !GetAtt KinesisAnalyticsRole.Arn
        Name: POWER_ANOMALY_STREAM

  # Ingest Data Delivery Stream
  processedDataDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      S3DestinationConfiguration:
        BucketARN: !GetAtt ProcessedDataBucket.Arn
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 100
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref IoTDataProcessingLogGroup
          LogStreamName: "processedDataS3Delivery"
        CompressionFormat: "UNCOMPRESSED"
        EncryptionConfiguration:
          NoEncryptionConfig: "NoEncryption"
        Prefix: "processed-data/"
        RoleARN: !GetAtt processedDataDeliveryStreamRole.Arn

  S3NotificationLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda_functions/s3_notification_receiver
      Handler: lambda.lambda_handler
      Runtime: python3.12
      Description: Invokes Sagemaker endpoint as new data arrives in S3.
      MemorySize: 256
      Role: !GetAtt LambdaIAMRole.Arn
      Timeout: 300

  ########################################################################
  # IAM Roles & Logs
  ########################################################################
  # Logs
  IoTDataProcessingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  IoTDataProcessingLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref IoTDataProcessingLogGroup

  IngestDataDeliveryStreamRole: # To change not sure how (actually no need can keep as it as this is only for writing to S3 and for cloudwatch)
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        # Puts objects in IngestDataBucket
        - PolicyName: "IngestDataS3UploadPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                Resource:
                  - !Sub "${IngestDataBucket.Arn}"
                  - !Sub "${IngestDataBucket.Arn}/"
                  - !Sub "${IngestDataBucket.Arn}/*"

        # Write to CloudWatch
        - PolicyName: IngestDataDeliveryStreamLogging
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutDestination
                  - logs:PutLogEvents
                Resource: !Join
                  - ""
                  - - "arn:aws:logs:"
                    - !Ref AWS::Region
                    - ":"
                    - !Ref AWS::AccountId
                    - ":log-group:*"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "The wildcard action in the logs policy is required"

  processedDataDeliveryStreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        # Puts objects in IngestDataBucket
        - PolicyName: "processedDataS3UploadPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                Resource:
                  - !Sub "${ProcessedDataBucket.Arn}"
                  - !Sub "${ProcessedDataBucket.Arn}/"
                  - !Sub "${ProcessedDataBucket.Arn}/*"

        # Write to CloudWatch
        - PolicyName: IngestDataDeliveryStreamLogging
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutDestination
                  - logs:PutLogEvents
                Resource: !Join
                  - ""
                  - - "arn:aws:logs:"
                    - !Ref AWS::Region
                    - ":"
                    - !Ref AWS::AccountId
                    - ":log-group:*"

  IoTTopicRuleRole: # Need to change and update for Kinesis DataStream
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "iot.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        # Posts to IngestDataDeliveryStream
        - PolicyName: "IoTTopicRulePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Effect: Allow
              Action:
                - firehose:DescribeDeliveryStream
                - firehose:ListDeliveryStreams
                - firehose:PutRecord
                - firehose:PutRecordBatch
              Resource: !Sub "${IngestDataDeliveryStream.Arn}"
        - PolicyName: "IoTTopicRuleKinesisPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "kinesis:PutRecord"
                  - "kinesis:PutRecords"
                Resource:
                  - !GetAtt RawDataIngestStream.Arn

  KinesisAnalyticsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: kinesisanalytics.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: Open
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - ProcessedDataBucket
      - S3NotificationLambdaFunction
    Properties:
      FunctionName: !GetAtt S3NotificationLambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub "arn:aws:s3:::${ProcessedDataBucket}"

  LambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                  - "sagemaker:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

Outputs:
  IngestDataDeliveryStreamArn:
    Description: Arn of Ingest Data Delivery Stream
    Value: !GetAtt IngestDataDeliveryStream.Arn
    Export:
      Name: !Sub "${AWS::StackName}-IngestDataDeliveryStreamArn"
  ProcessedDataBucketArn:
    Description: Arn of S3 bucket for processed data
    Value: !GetAtt ProcessedDataBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ProcessedDataBucketArn"
  IoTDataProcessingLogGroup:
    Description: Log Group Name for logging
    Value: !Ref IoTDataProcessingLogGroup
    Export:
      Name: !Sub "${AWS::StackName}-IoTDataProcessingLogGroup"
